In [1]:
import pandas as pd

df = pd.read_csv('liverpool.csv')

In [55]:
df

Name Position  Born  Number Nationality
0  Roberto Firmino       FW  1991   no. 9      Brazil
1       Sadio Mane       FW  1992  no. 10     Senegal
2    Mohamed Salah       FW  1992  no. 11       Egypt
3        Joe Gomez       DF  1997  no. 12     England
4   Alisson Becker       GK  1992  no. 13      Brazil

In [2]:
import numpy as np

a1 = np.full(6,0)
a2 = np.zeros(6, dtype=int) # zeros도 가능하지만 ones도 가능함
a3 = np.ones(6, dtype=int)
# 이 두개는 같은것임

print(a1) 
print(a2)
print(a3)

[0 0 0 0 0 0]
[0 0 0 0 0 0]
[1 1 1 1 1 1]


In [18]:
a1 = np.random.random(6)
a2 = np.random.randint(1, 10, 3) # 1 부터 10까지 랜덤으로 3개를 만든다.

# np에 random이라는 모듈이 있고 그 안에 또 random 이라는 함수가 있음.

print(a1) 
print(a2)

[0.82770436 0.87848339 0.07718767 0.76523445 0.26696513 0.64600598]
[2 1 3]


In [9]:
a1 = np.arange(2, 15, 3)
print(a1)

[ 2  5  8 11 14]


#### 부대찌개 문제

In [23]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000,440000, 140000, 180000, 340000,330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000,400000, 350000, 380000, 150000,110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000,360000, 320000, 250000]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 2100, 1400, 1500, 2100, 1500, 1500, 2300, 2100, 2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 2200, 2400, 2100, 2800, 1900, 2100, 1800, 2200, 2100, 1600, 1800]

# 코드를 작성하세요.
won_array = np.array(revenue_in_yen) * 10.08 + np.array(revenue_in_dollar) * 1138

# 정답 출력
won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

#### booleans 연습

In [24]:
a1 = np.arange(1, 10)
a1 % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False])

In [28]:
booleans = np.array([False,  True, False,  True, False,  True, False,  True, False])
np.where(booleans)

(array([1, 3, 5, 7], dtype=int64),)

In [31]:
filter = np.where(booleans)
a1[filter] # 이거도 가능함, True인 인덱스만 가져오는 것임

array([2, 4, 6, 8])

#### 또 다른 부대찌개 문제

In [47]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.

booleans = np.array(revenue_in_yen) < 200000
filter = np.where(booleans)
bad_days_revenue = np.array(revenue_in_yen)[filter]

# 정답 출력
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

In [52]:
# 최댓값, 최솟값, 평균값, 중앙값, 표준 편차, 분산
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.max()) # 최댓값
print(array1.min()) # 최솟값
print(array1.mean()) # 평균값
print(np.median(array1)) # 중앙값
print(array1.std()) # 표준 편차
print(array1.var()) # 분산

31
5
15.25
13.5
8.496322733983215
72.1875


#### DataFrame

In [62]:
two_dimensional_list = [['dongwook', 50, 86], ['sineui', 89, 31], ['ikjoong', 68, 91], ['yoonsoo', 88, 75]]
two_dimensional_array = np.array(two_dimensional_list)
df2 = pd.DataFrame(two_dimensional_array)
df2

0   1   2
0  dongwook  50  86
1    sineui  89  31
2   ikjoong  68  91
3   yoonsoo  88  75

In [58]:
names = ['dongwook', 'sineui', 'ikjoong', 'yoonsoo']
english_scores = [50, 89, 68, 88]
math_scores = [86, 31, 91, 75]

dict1 = {
    'name': names, 
    'english_score': english_scores, 
    'math_score': math_scores
}

dict2 = {
    'name': np.array(names), 
    'english_score': np.array(english_scores), 
    'math_score': np.array(math_scores)
}

dict3 = {
    'name': pd.Series(names), 
    'english_score': pd.Series(english_scores), 
    'math_score': pd.Series(math_scores)
}


# 아래 셋은 모두 동일합니다
df1 = pd.DataFrame(dict1)
df2 = pd.DataFrame(dict2)
df3 = pd.DataFrame(dict3)

df1

name  english_score  math_score
0  dongwook             50          86
1    sineui             89          31
2   ikjoong             68          91
3   yoonsoo             88          75

In [59]:
my_list = [
    {'name': 'dongwook', 'english_score': 50, 'math_score': 86},
    {'name': 'sineui', 'english_score': 89, 'math_score': 31},
    {'name': 'ikjoong', 'english_score': 68, 'math_score': 91},
    {'name': 'yoonsoo', 'english_score': 88, 'math_score': 75}
]

df = pd.DataFrame(my_list)
df

name  english_score  math_score
0  dongwook             50          86
1    sineui             89          31
2   ikjoong             68          91
3   yoonsoo             88          75

#### 실습과제

In [70]:
import pandas as pd

df = np.array([['Taylor Swift', 'December 13, 1989', 'Singer-songwriter'],['Aaron Sorkin', 'June 9, 1961', 'Screenwriter'],
['Harry Potter','July 31, 1980', 'Wizard'], ['Ji-Sung Park', 'February 25, 1981','Footballer']])

df1 = pd.DataFrame(df, columns = ['name', 'birthday', 'occupation'])
df1

name           birthday         occupation
0  Taylor Swift  December 13, 1989  Singer-songwriter
1  Aaron Sorkin       June 9, 1961       Screenwriter
2  Harry Potter      July 31, 1980             Wizard
3  Ji-Sung Park  February 25, 1981         Footballer

In [79]:
df = [
    {'name' : 'Taylor Swift', 'birthday' : 'December 13, 1989', 'occupation' : 'Singer-songwriter'},
    {'name' : 'Aaron Sorkin', 'birthday' : 'June 9, 1961', 'occupation' : 'Screenwriter'},
    {'name' : 'Harry Potter', 'birthday' : 'July 31, 1980', 'occupation' : 'Wizard'},
    {'name' : 'Ji-Sung Park', 'birthday' : 'February 25, 1981', 'occupation' : 'Footballer'}
]

pd.DataFrame(df)

name           birthday         occupation
0  Taylor Swift  December 13, 1989  Singer-songwriter
1  Aaron Sorkin       June 9, 1961       Screenwriter
2  Harry Potter      July 31, 1980             Wizard
3  Ji-Sung Park  February 25, 1981         Footballer

In [82]:
celebrities = [
    ['Taylor Swift', 'December 13, 1989', 'Singer-songwriter'],
    ['Aaron Sorkin', 'June 9, 1961', 'Screenwriter'],
    ['Harry Potter', 'July 31, 1980', 'Wizard'],
    ['Ji-Sung Park', 'February 25, 1981', 'Footballer']
]

df = pd.DataFrame(celebrities, columns=['name', 'birthday', 'occupation'])
df # 정답 출력

name           birthday         occupation
0  Taylor Swift  December 13, 1989  Singer-songwriter
1  Aaron Sorkin       June 9, 1961       Screenwriter
2  Harry Potter      July 31, 1980             Wizard
3  Ji-Sung Park  February 25, 1981         Footballer

In [83]:
# 데이터 타입을 볼 수 있음.
df.dtypes

name          object
birthday      object
occupation    object
dtype: object

### csv 파일 가져오기

In [3]:
import pandas as pd

In [4]:
iphone_df = pd.read_csv('iphone.csv') # csv의 첫번째 파일은 해더임 header = ~~ 
iphone_df 

Unnamed: 0         출시일  디스플레이  메모리     출시 버전 Face ID
0       iPhone 7  2016-09-16    4.7  2GB  iOS 10.0      No
1  iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
2       iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No
3  iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
4       iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes
5      iPhone XS  2018-09-21    5.8  4GB  iOS 12.0     Yes
6  iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [5]:
type(iphone_df)

pandas.core.frame.DataFrame

In [ ]:
# 지금은 컬럼 o